language: csharp
solution: TessClass.sln
install:
  - nuget restore TessClass.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TessClass.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TessClass/bin/Release/TessClass.Tests.dll